#Conference types
CONFTYPE_symmetric  = "symmetric"
CONFTYPE_asymmetric = "assymetric"                        
CONFTYPE_role       = "role"

CAUSE = {
    0: "Your call has been rejected",
    1: "Maximum number of conference participants is reached",
    2: "Participant is busy",
    3: "User is not available now",
    4: "Invalid conference",
    5: "User not found",
    6: "JOIN_OK",
    7: "Insufficient funds",
    8: "Access denied",
    9: "Rejected by logout",
    10: "The action cannot be completed",
    11: "Rejected by local resource limit",
    12: "Enter conference password",
    13: "Wrong password",
    14: "The user has rejected your call",
    15: "Rejected by bad rating",
    16: "The user does not answer",
    17: "Conference is not active yet",
    18: "Conference is over",
    19: "Conference not found",
    20: "Conference type is not supported"
}

'''
  All Events
'''
EV_abReceivedAfterLogin = "abReceivedAfterLogin"
EV_allSlidesCachingStopped = "allSlidesCachingStopped"
EV_allSlidesRemoved = "allSlidesRemoved"
EV_appSndDevChanged = "appSndDevChanged"
EV_appStateChanged = "appStateChanged"
EV_appUpdateAvailable = "appUpdateAvailable"
EV_audioCapturerMute = "audioCapturerMute"
EV_audioDelayDetectorTestStateChanged = "audioDelayDetectorTestStateChanged"
EV_audioRendererMute = "audioRendererMute"
EV_authorizationNeeded = "authorizationNeeded"
EV_availableServersListLoaded = "availableServersListLoaded"
EV_backgroundImageChanged = "backgroundImageChanged"
EV_broadcastPictureStateChanged = "broadcastPictureStateChanged"
EV_broadcastSelfieChanged = "broadcastSelfieChanged"
EV_callHistoryCleared = "callHistoryCleared"
EV_cameraStateChangedByConferenceOwner = "cameraStateChangedByConferenceOwner"
EV_chatMessageSent = "chatMessageSent"
EV_cmdChatClear = "cmdChatClear"
EV_commandReceived = "commandReceived"
EV_commandSent = "commandSent"
EV_conferenceCreated = "conferenceCreated"
EV_conferenceDeleted = "conferenceDeleted"
EV_conferenceList = "conferenceList"
EV_contactBlocked = "contactBlocked"
EV_contactsAdded = "contactsAdded"
EV_contactsDeleted = "contactsDeleted"
EV_contactsRenamed = "contactsRenamed"
EV_contactUnblocked = "contactUnblocked"
EV_cropChanged = "cropChanged"
EV_currentSlideIndexChanged = "currentSlideIndexChanged"
EV_currentUserDisplayNameChanged = "currentUserDisplayNameChanged"
EV_currentUserProfileUrlChanged = "currentUserProfileUrlChanged"
EV_customLogoUsageChanged = "customLogoUsageChanged"
EV_dataDeleted = "dataDeleted"
EV_dataSaved = "dataSaved"
EV_detailsInfo = "detailsInfo"
EV_deviceModesDone = "deviceModesDone"
EV_deviceStatusReceived = "deviceStatusReceived"
EV_downloadProgress = "downloadProgress"
EV_dsStarted = "dsStarted"
EV_dsStopped = "dsStopped"
EV_enableAudioReceivingChanged = "enableAudioReceivingChanged"
EV_enableVideoReceivingChanged = "enableVideoReceivingChanged"
EV_extraVideoFlowNotify = "extraVideoFlowNotify"
EV_fileAccepted = "fileAccepted"
EV_fileConferenceSent = "fileConferenceSent"
EV_fileDownloadingProgress = "fileDownloadingProgress"
EV_fileRejected = "fileRejected"
EV_fileSent = "fileSent"
EV_fileStatus = "fileStatus"
EV_fileTransferAvailable = "fileTransferAvailable"
EV_fileTransferCleared = "fileTransferCleared"
EV_fileTransferFileDeleted = "fileTransferFileDeleted"
EV_fileTransferPinChanged = "fileTransferPinChanged"
EV_fileUploadingProgress = "fileUploadingProgress"
EV_groupChatMessageSent = "groupChatMessageSent"
EV_groupsAdded = "groupsAdded"
EV_groupsRemoved = "groupsRemoved"
EV_groupsRenamed = "groupsRenamed"
EV_hangUpPressed = "hangUpPressed"
EV_hardwareChanged = "hardwareChanged"
EV_hookOffPressed = "hookOffPressed"
EV_httpServerSettingChanged = "httpServerSettingChanged"
EV_httpServerStateChanged = "httpServerStateChanged"
EV_imageAddedToCachingQueue = "imageAddedToCachingQueue"
EV_imageRemovedFromCachingQueue = "imageRemovedFromCachingQueue"
EV_incomingChatMessage = "incomingChatMessage"
EV_incomingGroupChatMessage = "incomingGroupChatMessage"
EV_incomingPodiumInvitationRemoved = "incomingPodiumInvitationRemoved"
EV_incomingRequestCameraControlAccepted = "incomingRequestCameraControlAccepted"
EV_incomingRequestCameraControlRejected = "incomingRequestCameraControlRejected"
EV_incomingRequestToPodiumAnswered = "incomingRequestToPodiumAnswered"
EV_inviteReceived = "inviteReceived"
EV_inviteRequestSent = "inviteRequestSent"
EV_inviteSent = "inviteSent"
EV_joinToConferenceLinkReceived = "joinToConferenceLinkReceived"
EV_lastCallsViewed = "lastCallsViewed"
EV_licenseActivation = "licenseActivation"
EV_licenseStatusChanged = "licenseStatusChanged"
EV_login = "login"
EV_logoImageChanged = "logoImageChanged"
EV_logout = "logout"
EV_micStateChangedByConferenceOwner = "micStateChangedByConferenceOwner"
EV_monitorsInfoUpdated = "monitorsInfoUpdated"
EV_myEvent = "myEvent"
EV_mySlideShowStarted = "mySlideShowStarted"
EV_mySlideShowStopped = "mySlideShowStopped"
EV_mySlideShowTitleChanged = "mySlideShowTitleChanged"
EV_NDIDeviceCreated = "NDIDeviceCreated"
EV_NDIDeviceDeleted = "NDIDeviceDeleted"
EV_NDIStateChanged = "NDIStateChanged"
EV_newParticipantInConference = "newParticipantInConference"
EV_outgoingBitrateChanged = "outgoingBitrateChanged"
EV_outgoingRequestCameraControlAccepted = "outgoingRequestCameraControlAccepted"
EV_outgoingRequestCameraControlRejected = "outgoingRequestCameraControlRejected"
EV_outputSelfVideoRotateAngleChanged = "outputSelfVideoRotateAngleChanged"
EV_participantLeftConference = "participantLeftConference"
EV_peerAccepted = "peerAccepted"
EV_propertiesUpdated = "propertiesUpdated"
EV_ptzControlsChanged = "ptzControlsChanged"
EV_realtimeManagmentUrlAvailabilityChanged = "realtimeManagmentUrlAvailabilityChanged"
EV_receivedFileRequest = "receivedFileRequest"
EV_receiversInfoUpdated = "receiversInfoUpdated"
EV_recordRequest = "recordRequest"
EV_recordRequestReply = "recordRequestReply"
EV_rejectReceived = "rejectReceived"
EV_rejectSent = "rejectSent"
EV_remarkCountDown = "remarkCountDown"
EV_remotelyControlledCameraNotAvailableAnymore = "remotelyControlledCameraNotAvailableAnymore"
EV_requestCameraControlReceived = "requestCameraControlReceived"
EV_requestCameraControlSent = "requestCameraControlSent"
EV_requestInviteReceived = "requestInviteReceived"
EV_roleEventOccured = "roleEventOccured"
EV_serverConnected = "serverConnected"
EV_serverDisconnected = "serverDisconnected"
EV_settingsChanged = "settingsChanged"
EV_showCurrentUserWidget = "showCurrentUserWidget"
EV_showIncomingRequestWidget = "showIncomingRequestWidget"
EV_showInfoConnect = "showInfoConnect"
EV_showLogo = "showLogo"
EV_showTime = "showTime"
EV_showUpcomingMeetings = "showUpcomingMeetings"
EV_slideAdded = "slideAdded"
EV_slideCached = "slideCached"
EV_slideCachingStarted = "slideCachingStarted"
EV_slidePositionChanged = "slidePositionChanged"
EV_slideRemoved = "slideRemoved"
EV_slideShowAvailabilityChanged = "slideShowAvailabilityChanged"
EV_slideShowCleared = "slideShowCleared"
EV_slidesSorted = "slidesSorted"
EV_slideUploaded = "slideUploaded"
EV_stopCalling = "stopCalling"
EV_systemRatingUpdated = "systemRatingUpdated"
EV_tariffRestrictionsChanged = "tariffRestrictionsChanged"
EV_testAudioCapturerLevel = "testAudioCapturerLevel"
EV_testAudioCapturerStateChanged = "testAudioCapturerStateChanged"
EV_toneDial = "toneDial"
EV_updateAvatar = "updateAvatar"
EV_updateCameraInfo = "updateCameraInfo"
EV_updateFailed = "updateFailed"
EV_userRecordingMeStatusChanged = "userRecordingMeStatusChanged"
EV_usersAddedToGroups = "usersAddedToGroups"
EV_usersRemovedFromGroups = "usersRemovedFromGroups"
EV_usersStatusesChanged = "usersStatusesChanged"
EV_videoCapturerMute = "videoCapturerMute"
EV_videoMatrixChanged = "videoMatrixChanged"
EV_videoSlotMovedToMonitor = "videoSlotMovedToMonitor"
EV_videoSlotRemovedFromMonitor = "videoSlotRemovedFromMonitor"
EV_windowStateChanged = "windowStateChanged"

EVENT = {
    "ALL": {},
    EV_appStateChanged: {"event": "appStateChanged", "appState": None},
    EV_incomingChatMessage: {"event": "incomingChatMessage", "peerId": None, "peerDn": None, "message": None, "time": None, "method": "event"},
    EV_inviteReceived: {"event": "inviteReceived", "peerId": None, "peerDn": None, "type": None, "confId": None, "method": "event"},
    EV_rejectReceived: {"event": "rejectReceived", "cause": None, "peerId": None, "peerDn": None, "method": "event"}

}

'''
  All Methods
'''
M_accept = "accept"
M_acceptFile = "acceptFile"
M_acceptInvitationToPodium = "acceptInvitationToPodium"
M_acceptPeer = "acceptPeer"
M_acceptRequestCameraControl = "acceptRequestCameraControl"
M_acceptRequestToPodium = "acceptRequestToPodium"
M_activateLicense = "activateLicense"
M_addSlide = "addSlide"
M_addToAbook = "addToAbook"
M_addToGroup = "addToGroup"
M_allowRecord = "allowRecord"
M_auth = "auth"
M_block = "block"
M_call = "call"
M_cancelUpdate = "cancelUpdate"
M_changeCurrentMonitor = "changeCurrentMonitor"
M_changeVideoMatrix = "changeVideoMatrix"
M_changeVideoMatrixType = "changeVideoMatrixType"
M_changeWindowState = "changeWindowState"
M_chatClear = "chatClear"
M_checkFileTransferPIN = "checkFileTransferPIN"
M_clearCallHistory = "clearCallHistory"
M_clearFileTransfer = "clearFileTransfer"
M_clearTokens = "clearTokens"
M_connectToServer = "connectToServer"
M_connectToService = "connectToService"
M_createConference = "createConference"
M_createGroup = "createGroup"
M_createNDIDevice = "createNDIDevice"
M_deleteData = "deleteData"
M_deleteFileTransferFile = "deleteFileTransferFile"
M_deleteNDIDevice = "deleteNDIDevice"
M_denyRecord = "denyRecord"
M_enableAudioReceiving = "enableAudioReceiving"
M_enableVideoReceiving = "enableVideoReceiving"
M_expandCallToMulti = "expandCallToMulti"
M_fireMyEvent = "fireMyEvent"
M_getAbook = "getAbook"
M_getAllUserContainersNames = "getAllUserContainersNames"
M_getAppSndDev = "getAppSndDev"
M_getAppState = "getAppState"
M_getAudioDelayDetectorInfo = "getAudioDelayDetectorInfo"
M_getAudioMute = "getAudioMute"
M_getAudioReceivingLevel = "getAudioReceivingLevel"
M_getAuthInfo = "getAuthInfo"
M_getAvailableServersList = "getAvailableServersList"
M_getBackground = "getBackground"
M_getBanList = "getBanList"
M_getBroadcastPicture = "getBroadcastPicture"
M_getBroadcastSelfie = "getBroadcastSelfie"
M_getCallHistory = "getCallHistory"
M_getChatLastMessages = "getChatLastMessages"
M_getConferenceParticipants = "getConferenceParticipants"
M_getConferences = "getConferences"
M_getConnected = "getConnected"
M_getContactDetails = "getContactDetails"
M_getCreatedNDIDevices = "getCreatedNDIDevices"
M_getCrop = "getCrop"
M_getCurrentUserProfileUrl = "getCurrentUserProfileUrl"
M_getDisplayNameById = "getDisplayNameById"
M_getFileInfo = "getFileInfo"
M_getFileList = "getFileList"
M_getFileRequests = "getFileRequests"
M_getFileTransferAvailability = "getFileTransferAvailability"
M_getFileTransferInfo = "getFileTransferInfo"
M_getFileTransferPIN = "getFileTransferPIN"
M_getFileUploads = "getFileUploads"
M_getGroups = "getGroups"
M_getHardware = "getHardware"
M_getHardwareKey = "getHardwareKey"
M_getHttpServerSettings = "getHttpServerSettings"
M_getHttpServerState = "getHttpServerState"
M_getIncomingCameraControlRequests = "getIncomingCameraControlRequests"
M_getInfoWidgetsState = "getInfoWidgetsState"
M_getLastCallsViewTime = "getLastCallsViewTime"
M_getLastSelectedConference = "getLastSelectedConference"
M_getLastUsedServersList = "getLastUsedServersList"
M_getLicenseServerStatus = "getLicenseServerStatus"
M_getLicenseType = "getLicenseType"
M_getListOfChats = "getListOfChats"
M_getLogin = "getLogin"
M_getLogo = "getLogo"
M_getMaxConfTitleLength = "getMaxConfTitleLength"
M_getMicMute = "getMicMute"
M_getModes = "getModes"
M_getMonitorsInfo = "getMonitorsInfo"
M_getNDIState = "getNDIState"
M_getOutgoingBitrate = "getOutgoingBitrate"
M_getOutgoingCameraControlRequests = "getOutgoingCameraControlRequests"
M_getOutputSelfVideoRotateAngle = "getOutputSelfVideoRotateAngle"
M_getProperties = "getProperties"
M_getPtzControls = "getPtzControls"
M_getRemotelyControlledCameras = "getRemotelyControlledCameras"
M_getRenderInfo = "getRenderInfo"
M_getScheduler = "getScheduler"
M_getServerDomain = "getServerDomain"
M_getSettings = "getSettings"
M_getShowFileTransferTools = "getShowFileTransferTools"
M_getSlideShowCache = "getSlideShowCache"
M_getSlideShowInfo = "getSlideShowInfo"
M_getSystemInfo = "getSystemInfo"
M_getTariffRestrictions = "getTariffRestrictions"
M_getTokenForHttpServer = "getTokenForHttpServer"
M_getTrueConfRoomProKey = "getTrueConfRoomProKey"
M_getUpdateInfo = "getUpdateInfo"
M_getVideoMatrix = "getVideoMatrix"
M_getVideoMute = "getVideoMute"
M_gotoPodium = "gotoPodium"
M_hangUp = "hangUp"
M_hideVideoSlot = "hideVideoSlot"
M_inviteToConference = "inviteToConference"
M_inviteToPodium = "inviteToPodium"
M_kickFromPodium = "kickFromPodium"
M_kickPeer = "kickPeer"
M_leavePodium = "leavePodium"
M_loadData = "loadData"
M_login = "login"
M_logout = "logout"
M_moveVideoSlotToMonitor = "moveVideoSlotToMonitor"
M_productRegistrationOffline = "productRegistrationOffline"
M_ptzDown = "ptzDown"
M_ptzLeft = "ptzLeft"
M_ptzRight = "ptzRight"
M_ptzStop = "ptzStop"
M_ptzUp = "ptzUp"
M_ptzZoomDec = "ptzZoomDec"
M_ptzZoomInc = "ptzZoomInc"
M_rebootSystem = "rebootSystem"
M_reject = "reject"
M_rejectFile = "rejectFile"
M_rejectInvitationToPodium = "rejectInvitationToPodium"
M_rejectPeer = "rejectPeer"
M_rejectRequestCameraControl = "rejectRequestCameraControl"
M_rejectRequestToPodium = "rejectRequestToPodium"
M_remotelyControlledCameraPtzDown = "remotelyControlledCameraPtzDown"
M_remotelyControlledCameraPtzLeft = "remotelyControlledCameraPtzLeft"
M_remotelyControlledCameraPtzRight = "remotelyControlledCameraPtzRight"
M_remotelyControlledCameraPtzUp = "remotelyControlledCameraPtzUp"
M_remotelyControlledCameraPtzZoomDec = "remotelyControlledCameraPtzZoomDec"
M_remotelyControlledCameraPtzZoomInc = "remotelyControlledCameraPtzZoomInc"
M_removeAllSlides = "removeAllSlides"
M_removeFromAbook = "removeFromAbook"
M_removeFromGroup = "removeFromGroup"
M_removeFromServersList = "removeFromServersList"
M_removeGroup = "removeGroup"
M_removeImageFromCachingQueue = "removeImageFromCachingQueue"
M_removeSlide = "removeSlide"
M_removeVideoSlotFromMonitor = "removeVideoSlotFromMonitor"
M_renameGroup = "renameGroup"
M_renameInAbook = "renameInAbook"
M_requestParticipantCameraControl = "requestParticipantCameraControl"
M_resetFileTransferPIN = "resetFileTransferPIN"
M_restoreWindow = "restoreWindow"
M_saveData = "saveData"
M_sendCommand = "sendCommand"
M_sendConferenceFile = "sendConferenceFile"
M_sendFile = "sendFile"
M_sendGroupMessage = "sendGroupMessage"
M_sendMessage = "sendMessage"
M_setAppSndDev = "setAppSndDev"
M_setAudioCapturer = "setAudioCapturer"
M_setAudioMute = "setAudioMute"
M_setAudioReceivingLevel = "setAudioReceivingLevel"
M_setAudioRenderer = "setAudioRenderer"
M_setAuthParams = "setAuthParams"
M_setBackground = "setBackground"
M_setBroadcastSelfie = "setBroadcastSelfie"
M_setCrop = "setCrop"
M_setDefaultBackground = "setDefaultBackground"
M_setDefaultLogo = "setDefaultLogo"
M_setHttpServerSettings = "setHttpServerSettings"
M_setLastCallsViewed = "setLastCallsViewed"
M_setLogo = "setLogo"
M_setMicMute = "setMicMute"
M_setModeratorRole = "setModeratorRole"
M_setModes = "setModes"
M_setNDIState = "setNDIState"
M_setOutputSelfVideoRotateAngle = "setOutputSelfVideoRotateAngle"
M_setPanPos = "setPanPos"
M_setPtzDefaults = "setPtzDefaults"
M_setSettings = "setSettings"
M_setShowFileTransferTools = "setShowFileTransferTools"
M_setSlidePosition = "setSlidePosition"
M_setTiltPos = "setTiltPos"
M_setUsedApiVersion = "setUsedApiVersion"
M_setVideoCapturer = "setVideoCapturer"
M_setVideoMute = "setVideoMute"
M_setZoomPos = "setZoomPos"
M_showFirstSlide = "showFirstSlide"
M_showLastSlide = "showLastSlide"
M_showNextSlide = "showNextSlide"
M_showPrevSlide = "showPrevSlide"
M_showSlide = "showSlide"
M_showVideoSlot = "showVideoSlot"
M_shutdown = "shutdown"
M_shutdownSystem = "shutdownSystem"
M_sortSlides = "sortSlides"
M_startAudioDelayDetectorTest = "startAudioDelayDetectorTest"
M_startBroadcastPicture = "startBroadcastPicture"
M_startCapture = "startCapture"
M_startHttpServer = "startHttpServer"
M_startRemark = "startRemark"
M_startSlideShow = "startSlideShow"
M_startUpdate = "startUpdate"
M_stopAudioDelayDetectorTest = "stopAudioDelayDetectorTest"
M_stopBroadcastPicture = "stopBroadcastPicture"
M_stopCachingAllImages = "stopCachingAllImages"
M_stopCapture = "stopCapture"
M_stopHttpServer = "stopHttpServer"
M_stopSlideShow = "stopSlideShow"
M_swapVideoSlots = "swapVideoSlots"
M_switchVideoFlow = "switchVideoFlow"
M_testAudioCapturerStart = "testAudioCapturerStart"
M_testAudioCapturerStop = "testAudioCapturerStop"
M_testAudioRenderer = "testAudioRenderer"
M_toneDial = "toneDial"
M_turnRemoteCamera = "turnRemoteCamera"
M_turnRemoteMic = "turnRemoteMic"
M_turnRemoteSpeaker = "turnRemoteSpeaker"
M_unblock = "unblock"

METHOD = {
    M_getAppState: {"method": "getAppState", "appState": None},
    M_getHardware: {
      "method": "getHardware",
      "audioCapturers": None,
      "currentAudioCapturerName": None,
      "currentAudioCapturerDescription": None,
      #"currentAudioCapturerType": None, # version 4.1 or later
      "audioRenderers": None,
      "currentAudioRendererName": None,
      "currentAudioRendererDescription": None,
      #"currentAudioRendererType": None, # version 4.1 or later
      "videoCapturers": None,
      "currentVideoCapturerName": None,
      "currentVideoCapturerDescription": None,
      "currentVideoCapturerType": None,
      "DSCaptureList": None,
      "result": None
    },
}